#!/usr/bin/env node
import { compile } from "json-schema-to-typescript";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(here, "..");
const repositoryRoot = resolve(packageRoot, "../..");
const schemaDirectory = process.env.JRO_SCHEMA_DIR ?? join(repositoryRoot, "schemas");
const outputDirectory = join(packageRoot, "src/generated");
const check = process.argv.includes("--check");

const files = readdirSync(schemaDirectory)
  .filter((file) => file.endsWith(".schema.json"))
  .sort();
if (files.length !== 11) {
  throw new Error(`Expected 11 schemas in ${schemaDirectory}, found ${files.length}`);
}

const banner = [
  "/* eslint-disable */",
  "/**",
  " * This file is generated from schemas/*.schema.json.",
  " * Do not edit this file by hand; run pnpm generate:types.",
  " */",
  "",
].join("\n");

if (!check) mkdirSync(outputDirectory, { recursive: true });
const expectedOutputs = new Set();

for (const file of files) {
  const schema = JSON.parse(readFileSync(join(schemaDirectory, file), "utf8"));
  const documentName = basename(file, ".schema.json")
    .split("-")
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join("");
  const outputFile = `${basename(file, ".schema.json")}.ts`;
  expectedOutputs.add(outputFile);
  const generated = await compile(schema, documentName, {
    cwd: schemaDirectory,
    banner,
    style: {
      semi: true,
      singleQuote: false,
      tabWidth: 2,
    },
  });
  const expected = generated.endsWith("\n") ? generated : `${generated}\n`;
  const target = join(outputDirectory, outputFile);
  if (check) {
    if (!existsSync(target) || readFileSync(target, "utf8") !== expected) {
      throw new Error(`Generated type is stale: ${target}. Run pnpm generate:types.`);
    }
  } else {
    writeFileSync(target, expected, "utf8");
  }
}

if (check && existsSync(outputDirectory)) {
  for (const file of readdirSync(outputDirectory)) {
    if (file.endsWith(".ts") && !expectedOutputs.has(file)) {
      throw new Error(`Unexpected generated type file: ${join(outputDirectory, file)}`);
    }
  }
}

if (!check) process.stdout.write(`Generated ${expectedOutputs.size} schema type modules.\n`);
