import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  canonicalJson,
  mapFindingToObservation,
  normalizeRunBundle,
  prefixedSha256,
} from "../packages/agent-feed-consumer/dist/index.js";
import {
  freezeP0CoverageIndex,
  P0_SOURCE_ROLE_PLAN_SHA256,
  preflightProvisionalPublicationBatch,
  PROVISIONAL_PUBLICATION_BATCH_VERSION,
} from "../packages/provisional-rules/dist/index.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const readJson = async (relativePath) =>
  JSON.parse(await fs.readFile(path.join(root, relativePath), "utf8"));
const bundle = await readJson(
  "fixtures/m3/agent-feed/p0-seveneleven-payment-families.run-bundle.v0.1.json",
);
const candidateSet = await readJson(
  "fixtures/m3/provisional/p0-seveneleven-payment-family-candidates.v0.1.json",
);
const coverage = freezeP0CoverageIndex(
  await readJson("fixtures/m3/provisional/p0-coverage-index.v0.1.json"),
);
const importedAt = "2026-08-21T04:51:00.000Z";
const publishedAt = "2026-08-21T04:53:00Z";
const normalized = await normalizeRunBundle(bundle, {
  imported_at: importedAt,
});
const delivery = normalized.deliveries.find(
  (item) => item.event.event_type === "finding.submitted",
);
if (!delivery) throw new Error("payment-family finding delivery missing");
const finding = delivery.event.payload.finding;
const evidence = delivery.event.payload.submitted_evidence?.[0];
const mapped = mapFindingToObservation({
  event: delivery.event,
  finding,
  submitted_evidence: delivery.event.payload.submitted_evidence,
  received_at: importedAt,
});
if (!mapped || !evidence) throw new Error("payment-family mapping incomplete");

const preflight = preflightProvisionalPublicationBatch({
  version: PROVISIONAL_PUBLICATION_BATCH_VERSION,
  batch_id: "batch_p0_seveneleven_payment_families_20260821",
  plan_sha256: P0_SOURCE_ROLE_PLAN_SHA256,
  published_at: publishedAt,
  members: candidateSet.candidates.map((item) => ({
    member_id: `p0_seveneleven_${item.payment_family}`,
    admission_request: {
      candidate: item.candidate,
      observation: mapped.observation,
      p0_coverage_index: coverage,
    },
  })),
});
if (!preflight.ok)
  throw new Error(`candidate batch rejected: ${JSON.stringify(preflight.issues)}`);

const candidatesById = new Map(
  candidateSet.candidates.map((item) => [item.candidate.candidate_id, item.candidate]),
);
const sqlBatch = {
  version: preflight.batch.version,
  batch_id: preflight.batch.batch_id,
  plan_sha256: preflight.batch.plan_sha256,
  published_at: preflight.batch.published_at,
  batch_hash: preflight.batch.batch_hash,
  members: preflight.batch.published.map((member) => ({
    member_id: member.member_id,
    candidate_hash: member.candidate_hash,
    definition_hash: member.definition_hash,
    candidate_payload: candidatesById.get(member.envelope.candidate.candidate_id),
  })),
};
if (sqlBatch.members.some((member) => member.candidate_payload === undefined))
  throw new Error("candidate batch projection incomplete");

const { attempt: _attempt, ...stableEvent } = delivery.event;
const payloadHash = prefixedSha256(canonicalJson(stableEvent));
const json = (value) => JSON.stringify(value, null, 2);
const sql = `-- Generated by scripts/generate_p0_payment_acceptance_seed.mjs.
-- One bounded manual Agent Feed run expands only the already evidenced
-- Seven-Eleven payment-acceptance family set. It publishes no earning rate,
-- campaign, selectable product SKU, or canonical RewardRuleVersion.

begin;

do $seed$
declare
    v_receipt_id uuid;
    v_observation_id uuid;
    v_mapping_status text;
    v_evidence jsonb := $evidence$${json(evidence)}$evidence$::jsonb;
begin
    if exists (
        select 1 from app_private.agent_feed_receipts
         where event_id = '${delivery.event_id}'
    ) or exists (
        select 1 from app_private.source_observations
         where observation_key = '${mapped.observation.observation_id}'
            or semantic_fingerprint = '${mapped.observation.semantic_fingerprint}'
    ) then
        raise exception 'P0 payment-family source run already exists; seed is one-time and drift-sensitive';
    end if;

    insert into app_private.agent_feed_receipts (
        event_id, protocol_version, stream_id, run_id, finding_id, event_type,
        received_at, payload_hash, raw_payload, retention_class, purge_after,
        delivery_id, signature_timestamp, signature_key_id, delivery_attempt,
        transport_payload_hash, signature_verified
    ) values (
        '${delivery.event_id}', '${delivery.event.protocol_version}',
        '${delivery.event.stream_id}', '${delivery.event.run_id}',
        '${delivery.event.finding_id}', '${delivery.event.event_type}',
        '${importedAt}', '${payloadHash}',
        $payload$${json(delivery.event.payload)}$payload$::jsonb,
        'local_run_bundle_import', '2026-09-20T04:51:00.000Z',
        '${delivery.delivery_id}', '${importedAt}',
        'local-run-bundle-unverified', 1, '${normalized.bundle_hash}', false
    ) returning id into v_receipt_id;

    insert into app_private.agent_feed_delivery_attempts (
        receipt_id, delivery_id, attempt_number, attempted_at,
        signature_timestamp, signature_key_id, transport_payload_hash,
        outcome, diagnostic, redaction_status, redacted_at
    ) values (
        v_receipt_id, '${delivery.delivery_id}', 1, '${importedAt}',
        '${importedAt}', 'local-run-bundle-unverified',
        '${normalized.bundle_hash}', 'replayed', '{}', 'complete', '${importedAt}'
    );

    select observation_id, mapping_status
      into v_observation_id, v_mapping_status
      from app_private.map_agent_feed_finding(
          v_receipt_id,
          '${mapped.observation.observation_id}',
          $sources$${json(mapped.observation.source_ids)}$sources$::jsonb,
          $subjects$${json(mapped.observation.subjects)}$subjects$::jsonb,
          '${mapped.observation.change_type}',
          ${`$summary$${mapped.observation.summary}$summary$`},
          $effective$${json(mapped.observation.effective_time)}$effective$::jsonb,
          $assessment$${json(mapped.observation.discovery_assessment)}$assessment$::jsonb,
          $evidence_refs$${json(mapped.observation.submitted_evidence_refs)}$evidence_refs$::jsonb,
          $attributes$${json(mapped.observation.raw_attributes)}$attributes$::jsonb,
          $flags$${json(mapped.observation.security_flags)}$flags$::jsonb,
          '${mapped.observation.semantic_fingerprint}', 1
      );
    if v_mapping_status is distinct from 'mapped' or v_observation_id is null then
        raise exception 'P0 payment-family finding did not map to a new observation';
    end if;

    update app_private.source_observations
       set status = 'needs_review'
     where id = v_observation_id;
    update app_private.source_observation_submitted_evidence
       set submitted_payload = v_evidence,
           promotion_status = 'lead_only'
     where observation_id = v_observation_id
       and agent_feed_evidence_id = '${evidence.evidence_id}';
    if not found then
        raise exception 'P0 payment-family evidence lead is missing';
    end if;
end
$seed$;

select app_private.publish_provisional_candidate_batch(
    $batch$${json(sqlBatch)}$batch$::jsonb
);

do $assert$
begin
    if (select count(*) from app_private.provisional_publication_batch_members
         where batch_id = '${sqlBatch.batch_id}') <> ${sqlBatch.members.length}
       or (select count(*) from app_api.active_experimental_provisional_publications
            where batch_id = '${sqlBatch.batch_id}') <> ${sqlBatch.members.length}
    then
        raise exception 'P0 payment-family batch did not publish all members';
    end if;
end
$assert$;

commit;
`;

await fs.writeFile(
  path.join(root, "db/seeds/004_p0_payment_acceptance_batch.sql"),
  sql,
  "utf8",
);
