#!/usr/bin/env node

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const target = resolve(
  root,
  "fixtures/m3/agent-feed/p0-exchange-route-completeness.research.v0.1.json",
);
const observedAt = "2026-08-25T21:30:00+09:00";

const sources = [
  {
    source_id: "jp.jal.ponta-benefit",
    family_id: "point.jal-mile",
    roles: ["eligible_cards", "transfer_partner_directory"],
    url: "https://www.jal.co.jp/jp/ja/jalmile/use/partner/ponta/",
    title: "Ponta特典（JMB×Ponta会員限定）",
    publisher: "日本航空株式会社",
    official_domain: "www.jal.co.jp",
    notes:
      "The official JAL benefit page supplies the two current JAL-mile to Ponta tiers, exchange units, minimum and membership requirement.",
  },
  {
    source_id: "jp.jrkyushu.point-exchange",
    family_id: "transit.jrkyushu",
    roles: ["eligible_cards", "transfer_partner_directory"],
    url: "https://www.jrkyushu.co.jp/point/exchange/",
    title: "提携ポイントとの交換について｜JRキューポ｜JR九州",
    publisher: "九州旅客鉄道株式会社",
    official_domain: "www.jrkyushu.co.jp",
    notes:
      "The official JR Kyushu exchange table supplies both directions, ratios, units and named card/account prerequisites for the represented P0 programmes.",
  },
  {
    source_id: "jp.moppy.exchange",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/cashback/",
    title: "ポイント交換",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official Moppy exchange directory supplies the current fee-free d-point and nanaco routes, minimums and processing windows.",
  },
  {
    source_id: "jp.moppy.v-fee-update",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/news/detail.php?category=2&news_id=3293",
    title: "Vポイントへの交換手数料変更のお知らせ",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official Moppy notice states a seven-percent exchange fee from 2026-04-01.",
  },
  {
    source_id: "jp.moppy.ana-exchange",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/cashback/detail.php?c_id=91",
    title: "ANAマイレージクラブに交換",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official Moppy detail page states 1,750 points to 500 ANA miles, no fee, a 1,750-point minimum and 1-to-3-day processing.",
  },
  {
    source_id: "jp.moppy.ponta-exchange",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/cashback/detail.php?c_id=49",
    title: "Pontaポイントに交換",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official Moppy detail page states a 1-to-1 rate, 315-point minimum, fee from 15 points and real-time processing.",
  },
  {
    source_id: "jp.moppy.paypay-exchange",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/cashback/detail.php?c_id=47",
    title: "PayPayポイントに交換",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official Moppy detail page states a 1-to-1 rate, 550-point minimum, fee from 50 points and real-time processing.",
  },
  {
    source_id: "jp.moppy.exchange-fee-help",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/help/detail/?id=37",
    title: "ポイント交換に手数料は必要？",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official help page states that exchange fees are deducted from the submitted Moppy-point amount.",
  },
  {
    source_id: "jp.moppy.rakuten-fee-update",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/news/detail.php?news_id=3283",
    title: "楽天ポイントへの交換手数料変更のお知らせ",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official Moppy notice states a ten-percent exchange fee from 2026-04-01.",
  },
  {
    source_id: "jp.moppy.waon-launch",
    family_id: "point.moppy",
    roles: ["transfer_partner_directory"],
    url: "https://pc.moppy.jp/news/detail.php?news_id=3086",
    title: "WAON POINTへのポイント交換を開始しました",
    publisher: "株式会社セレス",
    official_domain: "pc.moppy.jp",
    notes:
      "The official launch notice states the five supported exchange amounts and their two-percent fees.",
  },
  {
    source_id: "jp.jal.jr-kyupo-benefit",
    family_id: "point.jal-mile",
    roles: ["eligible_cards", "transfer_partner_directory"],
    url: "https://www.jal.co.jp/jp/ja/jalmile/use/partner/sugoca/",
    title: "JRキューポ特典",
    publisher: "日本航空株式会社",
    official_domain: "www.jal.co.jp",
    notes:
      "The official JAL benefit page states both tiers and the 30,000-mile April-to-March limit.",
  },
  {
    source_id: "jp.ana.jr-kyupo-benefit",
    family_id: "point.ana-mile",
    roles: ["eligible_cards", "transfer_partner_directory"],
    url: "https://www.ana.co.jp/ja/jp/shoppingandlife/point/tukau_sugoca/",
    title: "JRキューポに交換する",
    publisher: "全日本空輸株式会社",
    official_domain: "www.ana.co.jp",
    notes:
      "The official ANA page states the 10,000-mile unit, processing time and first-two versus third-and-later fiscal-year tiers.",
  },
  {
    source_id: "jp.ana.partner-exchange-rules",
    family_id: "point.ana-mile",
    roles: ["transfer_partner_directory"],
    url: "https://www.ana.co.jp/ja/jp/shoppingandlife/point/tukau_cap/",
    title: "提携ポイントへの交換条件",
    publisher: "全日本空輸株式会社",
    official_domain: "www.ana.co.jp",
    notes:
      "The official common rule page defines the April-to-March cumulative tier counter shared by eligible partner exchanges.",
  },
  {
    source_id: "jp.recruitpoint.d-transfer",
    family_id: "point.recruit",
    roles: ["eligible_accounts", "transfer_partner_directory"],
    url: "https://img.point.recruit.co.jp/recruitid/doc/point_partners/dpoint.html",
    title: "リクルートポイントからdポイントに交換する",
    publisher: "株式会社リクルート",
    official_domain: "img.point.recruit.co.jp",
    notes:
      "The official detail page states 1 Recruit point to 1 d point, one-point minimum and increment, immediate processing and required account linkage.",
  },
  {
    source_id: "jp.recruitpoint.exchange-partners",
    family_id: "point.recruit",
    roles: ["transfer_partner_directory"],
    url: "https://point.recruit.co.jp/recruitid/doc/point_partners/",
    title: "交換できる提携ポイント・交換レート",
    publisher: "株式会社リクルート",
    official_domain: "point.recruit.co.jp",
    notes:
      "The official partner directory lists both Ponta and d point as outbound Recruit Point exchange destinations.",
  },
].map((source) => ({
  ...source,
  retrieval: {
    status: "fetched",
    accessed_at: observedAt,
    http_status: 200,
    content_type: "text/html",
    failure_reason: null,
  },
}));

const applicability = Object.freeze({
  status: "current_as_observed",
  effective_from: null,
  effective_to: null,
  timezone: "Asia/Tokyo",
});

function prerequisite({
  id,
  family,
  role = "eligible_cards",
  sourceIds,
  prerequisiteId,
  subject,
  predicate,
  condition,
  locator,
}) {
  return {
    claim_id: id,
    family_id: family,
    source_role_id: role,
    source_ids: sourceIds,
    claim_type: "eligibility",
    subject,
    predicate,
    value: { prerequisite_id: prerequisiteId, condition_ja: condition },
    applicability,
    exclusions: [],
    evidence_locator: locator,
    short_paraphrase: condition,
  };
}

function route({
  id,
  family,
  sourceIds,
  routeId,
  subject,
  sourceAsset,
  destinationAsset,
  sourceUnits,
  destinationUnits,
  minimum,
  increment,
  allowedSourceAmounts,
  maximum = null,
  periodMaximum = null,
  maximumPeriod = null,
  fee = 0,
  feeSchedule,
  periodUsageKey,
  periodUsageMin,
  periodUsageMax,
  processingMin = null,
  processingMax = null,
  prerequisiteIds = [],
  requiresRuleIds = [],
  conditions = [],
  validFrom = null,
  locator,
}) {
  return {
    claim_id: id,
    family_id: family,
    source_role_id: "transfer_partner_directory",
    source_ids: sourceIds,
    claim_type: "transfer_rule",
    subject,
    predicate: "converts_at_fixed_ratio",
    value: {
      transfer: {
        route_id: routeId,
        operation: "transfer",
        source_asset_ref: sourceAsset,
        destination_asset_ref: destinationAsset,
        source_units: sourceUnits,
        destination_units: destinationUnits,
        minimum_source_units: minimum,
        increment_source_units: increment,
        ...(allowedSourceAmounts === undefined
          ? {}
          : { allowed_source_amounts: allowedSourceAmounts }),
        maximum_source_units_per_request: maximum,
        maximum_source_units_per_period: periodMaximum,
        maximum_period: maximumPeriod,
        fee_source_units: fee,
        ...(feeSchedule === undefined ? {} : { fee_schedule: feeSchedule }),
        ...(periodUsageKey === undefined
          ? {}
          : { period_usage_key: periodUsageKey }),
        ...(periodUsageMin === undefined
          ? {}
          : { period_usage_min_source_units: periodUsageMin }),
        ...(periodUsageMax === undefined
          ? {}
          : { period_usage_max_source_units_exclusive: periodUsageMax }),
        processing_time_days_min: processingMin,
        processing_time_days_max: processingMax,
        cancellation_policy: "provider_defined",
        validity: {
          valid_from: validFrom,
          valid_to: null,
          timezone: "Asia/Tokyo",
        },
        prerequisite_ids: prerequisiteIds,
        requires_rule_ids: requiresRuleIds,
        required_conditions_ja: conditions,
        requires_direct_source: false,
        partial_consumption: true,
      },
    },
    applicability: {
      ...applicability,
      effective_from: validFrom,
    },
    exclusions: [],
    evidence_locator: locator,
    short_paraphrase: `${subject}の公式交換条件を計算経路として表現します。`,
  };
}

const jrSource = ["jp.jrkyushu.point-exchange"];
const claims = [
  prerequisite({
    id: "claim.route.prerequisite.recruit-d-link.001",
    family: "point.recruit",
    role: "eligible_accounts",
    sourceIds: ["jp.recruitpoint.d-transfer"],
    prerequisiteId: "prereq.recruit-d-account-link",
    subject: "リクルートIDとdアカウントの連携",
    predicate: "requires_recruit_and_d_account_linkage",
    condition: "リクルートIDにdアカウントを連携していること。",
    locator: "Recruit d-point transfer detail: target account requirement",
  }),
  prerequisite({
    id: "claim.route.prerequisite.jmb-ponta-link.001",
    family: "point.jal-mile",
    sourceIds: ["jp.jal.ponta-benefit"],
    prerequisiteId: "prereq.jmb-ponta-link",
    subject: "JMB×Ponta会員登録",
    predicate: "requires_jmb_ponta_linkage",
    condition: "JMB×Ponta会員としてJMB番号とPonta会員IDを連携していること。",
    locator: "JAL Ponta benefit: eligible member section",
  }),
  prerequisite({
    id: "claim.route.prerequisite.bic-jq-sugoca.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    prerequisiteId: "prereq.bic-camera-jq-sugoca",
    subject: "BIC CAMERA JQ SUGOCA",
    predicate: "requires_bic_camera_jq_sugoca",
    condition: "BIC CAMERA JQ SUGOCAを保有し、JR九州Web会員IDとおまとめ登録していること。",
    locator: "JR Kyupo exchange table: Bic Point eligibility",
  }),
  prerequisite({
    id: "claim.route.prerequisite.aeon-sugoca.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    prerequisiteId: "prereq.aeon-sugoca",
    subject: "イオンSUGOCAカード",
    predicate: "requires_aeon_sugoca",
    condition: "イオンSUGOCAカードを保有し、JR九州Web会員IDとおまとめ登録していること。",
    locator: "JR Kyupo exchange table: WAON POINT eligibility",
  }),
  prerequisite({
    id: "claim.route.prerequisite.v-jr-link.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    prerequisiteId: "prereq.v-point-jr-link",
    subject: "Vポイント付与先カードの連携",
    predicate: "requires_v_point_card_linkage",
    condition: "JR九州Web会員情報にVポイントが貯まる対象カードを連携していること。",
    locator: "JR Kyupo exchange table: V Point destination account",
  }),
  prerequisite({
    id: "claim.route.prerequisite.jmb-jq-sugoca.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    prerequisiteId: "prereq.jmb-jq-sugoca",
    subject: "JMB JQ SUGOCA",
    predicate: "requires_jmb_jq_sugoca",
    condition: "JMB JQ SUGOCAを保有し、JR九州Web会員IDとおまとめ登録していること。",
    locator: "JR Kyupo exchange table: JAL Mileage Bank eligibility",
  }),
  prerequisite({
    id: "claim.route.prerequisite.jq-sugoca-ana.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    prerequisiteId: "prereq.jq-sugoca-ana",
    subject: "JQ SUGOCA ANA",
    predicate: "requires_jq_sugoca_ana",
    condition: "JQ SUGOCA ANAを保有し、JR九州Web会員IDとおまとめ登録していること。",
    locator: "JR Kyupo exchange table: ANA Mileage Club eligibility",
  }),
  route({
    id: "claim.route.recruit.d.001",
    family: "point.recruit",
    sourceIds: [
      "jp.recruitpoint.d-transfer",
      "jp.recruitpoint.exchange-partners",
    ],
    routeId: "recruit-to-d",
    subject: "リクルートポイント → dポイント",
    sourceAsset: "asset.point.recruit",
    destinationAsset: "asset.point.d",
    sourceUnits: 1,
    destinationUnits: 1,
    minimum: 1,
    increment: 1,
    processingMin: 0,
    processingMax: 0,
    prerequisiteIds: ["claim.route.prerequisite.recruit-d-link.001"],
    requiresRuleIds: ["prereq.recruit-d-account-link"],
    locator: "Recruit d-point transfer detail: rate, unit and immediate transfer",
  }),
  route({
    id: "claim.route.jal.ponta.low-tier.001",
    family: "point.jal-mile",
    sourceIds: ["jp.jal.ponta-benefit"],
    routeId: "jal-to-ponta-low-tier",
    subject: "JALマイル → Pontaポイント（3,000〜9,000マイル）",
    sourceAsset: "asset.mile.jal",
    destinationAsset: "asset.point.ponta",
    sourceUnits: 1000,
    destinationUnits: 500,
    minimum: 3000,
    increment: 1000,
    maximum: 9000,
    prerequisiteIds: ["claim.route.prerequisite.jmb-ponta-link.001"],
    requiresRuleIds: ["prereq.jmb-ponta-link"],
    locator: "JAL Ponta benefit: 3,000–9,000-mile tier",
  }),
  route({
    id: "claim.route.jal.ponta.high-tier.001",
    family: "point.jal-mile",
    sourceIds: ["jp.jal.ponta-benefit"],
    routeId: "jal-to-ponta-high-tier",
    subject: "JALマイル → Pontaポイント（10,000マイル単位）",
    sourceAsset: "asset.mile.jal",
    destinationAsset: "asset.point.ponta",
    sourceUnits: 10000,
    destinationUnits: 10000,
    minimum: 10000,
    increment: 10000,
    prerequisiteIds: ["claim.route.prerequisite.jmb-ponta-link.001"],
    requiresRuleIds: ["prereq.jmb-ponta-link"],
    locator: "JAL Ponta benefit: 10,000-mile tier",
  }),
  route({
    id: "claim.route.saison.jr-kyupo.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    routeId: "saison-permanent-to-jr-kyupo",
    subject: "永久不滅ポイント → JRキューポ",
    sourceAsset: "asset.point.saison-permanent",
    destinationAsset: "asset.point.jr-kyupo",
    sourceUnits: 200,
    destinationUnits: 1000,
    minimum: 200,
    increment: 200,
    prerequisiteIds: ["claim.route.prerequisite.jq-card-saison.001"],
    requiresRuleIds: ["prereq.jq-card-saison"],
    locator: "JR Kyupo exchange table: Saison Permanent Point inbound row",
  }),
  route({
    id: "claim.route.bic.jr-kyupo.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    routeId: "bic-to-jr-kyupo",
    subject: "ビックポイント → JRキューポ",
    sourceAsset: "asset.point.bic",
    destinationAsset: "asset.point.jr-kyupo",
    sourceUnits: 1500,
    destinationUnits: 1000,
    minimum: 1500,
    increment: 1500,
    prerequisiteIds: ["claim.route.prerequisite.bic-jq-sugoca.001"],
    requiresRuleIds: ["prereq.bic-camera-jq-sugoca"],
    locator: "JR Kyupo exchange table: Bic Point inbound row",
  }),
  route({
    id: "claim.route.waon.jr-kyupo.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    routeId: "waon-to-jr-kyupo",
    subject: "WAON POINT → JRキューポ",
    sourceAsset: "asset.point.waon",
    destinationAsset: "asset.point.jr-kyupo",
    sourceUnits: 1000,
    destinationUnits: 1000,
    minimum: 1000,
    increment: 1000,
    prerequisiteIds: ["claim.route.prerequisite.aeon-sugoca.001"],
    requiresRuleIds: ["prereq.aeon-sugoca"],
    locator: "JR Kyupo exchange table: WAON POINT inbound row",
  }),
  route({
    id: "claim.route.jr-kyupo.v.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    routeId: "jr-kyupo-to-v",
    subject: "JRキューポ → Vポイント",
    sourceAsset: "asset.point.jr-kyupo",
    destinationAsset: "asset.point.v",
    sourceUnits: 500,
    destinationUnits: 500,
    minimum: 500,
    increment: 500,
    prerequisiteIds: ["claim.route.prerequisite.v-jr-link.001"],
    requiresRuleIds: ["prereq.v-point-jr-link"],
    locator: "JR Kyupo exchange table: V Point outbound row",
  }),
  route({
    id: "claim.route.jr-kyupo.bic.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    routeId: "jr-kyupo-to-bic",
    subject: "JRキューポ → ビックポイント",
    sourceAsset: "asset.point.jr-kyupo",
    destinationAsset: "asset.point.bic",
    sourceUnits: 1000,
    destinationUnits: 1000,
    minimum: 1000,
    increment: 1000,
    prerequisiteIds: ["claim.route.prerequisite.bic-jq-sugoca.001"],
    requiresRuleIds: ["prereq.bic-camera-jq-sugoca"],
    locator: "JR Kyupo exchange table: Bic Point outbound row",
  }),
  route({
    id: "claim.route.jr-kyupo.jal.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    routeId: "jr-kyupo-to-jal",
    subject: "JRキューポ → JALマイル",
    sourceAsset: "asset.point.jr-kyupo",
    destinationAsset: "asset.mile.jal",
    sourceUnits: 1000,
    destinationUnits: 500,
    minimum: 1000,
    increment: 1000,
    prerequisiteIds: ["claim.route.prerequisite.jmb-jq-sugoca.001"],
    requiresRuleIds: ["prereq.jmb-jq-sugoca"],
    conditions: ["交換申込みは1日1回まで。"],
    locator: "JR Kyupo exchange table: JAL outbound row and daily frequency",
  }),
  route({
    id: "claim.route.jr-kyupo.ana.001",
    family: "transit.jrkyushu",
    sourceIds: jrSource,
    routeId: "jr-kyupo-to-ana",
    subject: "JRキューポ → ANAマイル",
    sourceAsset: "asset.point.jr-kyupo",
    destinationAsset: "asset.mile.ana",
    sourceUnits: 1000,
    destinationUnits: 500,
    minimum: 1000,
    increment: 1000,
    prerequisiteIds: ["claim.route.prerequisite.jq-sugoca-ana.001"],
    requiresRuleIds: ["prereq.jq-sugoca-ana"],
    conditions: ["交換申込みは1日1回まで。"],
    locator: "JR Kyupo exchange table: ANA outbound row and daily frequency",
  }),
  route({
    id: "claim.route.jal.jr-kyupo.low-tier.001",
    family: "point.jal-mile",
    sourceIds: ["jp.jal.jr-kyupo-benefit"],
    routeId: "jal-to-jr-kyupo-low-tier",
    subject: "JALマイル → JRキューポ（3,000〜9,000マイル）",
    sourceAsset: "asset.mile.jal",
    destinationAsset: "asset.point.jr-kyupo",
    sourceUnits: 3000,
    destinationUnits: 1500,
    minimum: 3000,
    increment: 3000,
    maximum: 9000,
    periodMaximum: 30000,
    maximumPeriod: "fiscal_year_april",
    periodUsageKey: "period.jal-jr-kyupo-fiscal-year",
    prerequisiteIds: ["claim.route.prerequisite.jmb-jq-sugoca.001"],
    requiresRuleIds: ["prereq.jmb-jq-sugoca"],
    conditions: ["年度（4月〜翌3月）の交換上限は合計30,000マイル。"],
    locator: "JAL JR Kyupo benefit: 3,000–9,000-mile tier and annual cap",
  }),
  route({
    id: "claim.route.jal.jr-kyupo.high-tier.001",
    family: "point.jal-mile",
    sourceIds: ["jp.jal.jr-kyupo-benefit"],
    routeId: "jal-to-jr-kyupo-high-tier",
    subject: "JALマイル → JRキューポ（10,000マイル単位）",
    sourceAsset: "asset.mile.jal",
    destinationAsset: "asset.point.jr-kyupo",
    sourceUnits: 10000,
    destinationUnits: 10000,
    minimum: 10000,
    increment: 10000,
    periodMaximum: 30000,
    maximumPeriod: "fiscal_year_april",
    periodUsageKey: "period.jal-jr-kyupo-fiscal-year",
    prerequisiteIds: ["claim.route.prerequisite.jmb-jq-sugoca.001"],
    requiresRuleIds: ["prereq.jmb-jq-sugoca"],
    conditions: ["年度（4月〜翌3月）の交換上限は合計30,000マイル。"],
    locator: "JAL JR Kyupo benefit: 10,000-mile tier and annual cap",
  }),
  route({
    id: "claim.route.ana.jr-kyupo.full-tier.001",
    family: "point.ana-mile",
    sourceIds: [
      "jp.ana.jr-kyupo-benefit",
      "jp.ana.partner-exchange-rules",
    ],
    routeId: "ana-to-jr-kyupo-full-tier",
    subject: "ANAマイル → JRキューポ（年度2口目まで）",
    sourceAsset: "asset.mile.ana",
    destinationAsset: "asset.point.jr-kyupo",
    sourceUnits: 10000,
    destinationUnits: 10000,
    minimum: 10000,
    increment: 10000,
    maximumPeriod: "fiscal_year_april",
    periodUsageKey: "period.ana-partner-fiscal-year",
    periodUsageMax: 20000,
    processingMin: 3,
    processingMax: 4,
    prerequisiteIds: ["claim.route.prerequisite.jq-sugoca-ana.001"],
    requiresRuleIds: ["prereq.jq-sugoca-ana"],
    conditions: ["年度（4月〜翌3月）の提携ポイント交換が2口目まで。"],
    locator: "ANA JR Kyupo benefit and common partner exchange rules: first two units",
  }),
  route({
    id: "claim.route.ana.jr-kyupo.reduced-tier.001",
    family: "point.ana-mile",
    sourceIds: [
      "jp.ana.jr-kyupo-benefit",
      "jp.ana.partner-exchange-rules",
    ],
    routeId: "ana-to-jr-kyupo-reduced-tier",
    subject: "ANAマイル → JRキューポ（年度3口目以降）",
    sourceAsset: "asset.mile.ana",
    destinationAsset: "asset.point.jr-kyupo",
    sourceUnits: 10000,
    destinationUnits: 5000,
    minimum: 10000,
    increment: 10000,
    maximumPeriod: "fiscal_year_april",
    periodUsageKey: "period.ana-partner-fiscal-year",
    periodUsageMin: 20000,
    processingMin: 3,
    processingMax: 4,
    prerequisiteIds: ["claim.route.prerequisite.jq-sugoca-ana.001"],
    requiresRuleIds: ["prereq.jq-sugoca-ana"],
    conditions: ["年度（4月〜翌3月）の提携ポイント交換が3口目以降。"],
    locator: "ANA JR Kyupo benefit and common partner exchange rules: third and later units",
  }),
  route({
    id: "claim.route.moppy.ana.001",
    family: "point.moppy",
    sourceIds: ["jp.moppy.ana-exchange", "jp.moppy.exchange"],
    routeId: "moppy-to-ana",
    subject: "モッピーポイント → ANAマイル",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.mile.ana",
    sourceUnits: 1750,
    destinationUnits: 500,
    minimum: 1750,
    increment: 1750,
    processingMin: 1,
    processingMax: 3,
    locator: "Moppy ANA Mileage Club detail: rate, minimum, fee and processing time",
  }),
  route({
    id: "claim.route.moppy.ponta.minimum.001",
    family: "point.moppy",
    sourceIds: [
      "jp.moppy.exchange",
      "jp.moppy.exchange-fee-help",
      "jp.moppy.ponta-exchange",
    ],
    routeId: "moppy-to-ponta-minimum",
    subject: "モッピーポイント → Pontaポイント（確認済み最小交換）",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.point.ponta",
    sourceUnits: 1,
    destinationUnits: 1,
    minimum: 300,
    increment: null,
    allowedSourceAmounts: [300],
    fee: 15,
    processingMin: 0,
    processingMax: 0,
    locator: "Moppy Ponta detail and fee help: exact minimum transaction",
  }),
  route({
    id: "claim.route.moppy.paypay.minimum.001",
    family: "point.moppy",
    sourceIds: [
      "jp.moppy.exchange",
      "jp.moppy.exchange-fee-help",
      "jp.moppy.paypay-exchange",
    ],
    routeId: "moppy-to-paypay-minimum",
    subject: "モッピーポイント → PayPayポイント（確認済み最小交換）",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.point.paypay",
    sourceUnits: 1,
    destinationUnits: 1,
    minimum: 500,
    increment: null,
    allowedSourceAmounts: [500],
    fee: 50,
    processingMin: 0,
    processingMax: 0,
    locator: "Moppy PayPay detail and fee help: exact minimum transaction",
  }),
  route({
    id: "claim.route.moppy.v.001",
    family: "point.moppy",
    sourceIds: ["jp.moppy.exchange", "jp.moppy.v-fee-update"],
    routeId: "moppy-to-v",
    subject: "モッピーポイント → Vポイント",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.point.v",
    sourceUnits: 500,
    destinationUnits: 500,
    minimum: 500,
    increment: 500,
    feeSchedule: {
      model: "percentage_of_source",
      numerator: 7,
      denominator: 100,
      rounding: "ceil",
    },
    processingMin: 0,
    processingMax: 0,
    validFrom: "2026-04-01",
    locator: "Moppy V Point fee notice: seven-percent fee from 2026-04-01",
  }),
  route({
    id: "claim.route.moppy.rakuten.001",
    family: "point.moppy",
    sourceIds: ["jp.moppy.exchange", "jp.moppy.rakuten-fee-update"],
    routeId: "moppy-to-rakuten",
    subject: "モッピーポイント → 楽天ポイント",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.point.rakuten",
    sourceUnits: 500,
    destinationUnits: 500,
    minimum: 500,
    increment: 500,
    feeSchedule: {
      model: "percentage_of_source",
      numerator: 10,
      denominator: 100,
      rounding: "ceil",
    },
    processingMin: 1,
    processingMax: 2,
    validFrom: "2026-04-01",
    locator: "Moppy Rakuten Point fee notice: ten-percent fee from 2026-04-01",
  }),
  route({
    id: "claim.route.moppy.waon.001",
    family: "point.moppy",
    sourceIds: ["jp.moppy.exchange", "jp.moppy.waon-launch"],
    routeId: "moppy-to-waon",
    subject: "モッピーポイント → WAON POINT",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.point.waon",
    sourceUnits: 1,
    destinationUnits: 1,
    minimum: 500,
    increment: null,
    allowedSourceAmounts: [500, 1000, 3000, 5000, 10000],
    feeSchedule: {
      model: "percentage_of_source",
      numerator: 2,
      denominator: 100,
      rounding: "ceil",
    },
    processingMin: 0,
    processingMax: 0,
    validFrom: "2025-07-18",
    locator: "Moppy WAON launch notice: five exact exchange amounts and two-percent fees",
  }),
  route({
    id: "claim.route.moppy.d.001",
    family: "point.moppy",
    sourceIds: ["jp.moppy.exchange"],
    routeId: "moppy-to-d",
    subject: "モッピーポイント → dポイント",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.point.d",
    sourceUnits: 500,
    destinationUnits: 500,
    minimum: 500,
    increment: 500,
    processingMin: 0,
    processingMax: 0,
    locator: "Moppy exchange directory: d Point row",
  }),
  route({
    id: "claim.route.moppy.nanaco.001",
    family: "point.moppy",
    sourceIds: ["jp.moppy.exchange"],
    routeId: "moppy-to-nanaco",
    subject: "モッピーポイント → nanacoポイント",
    sourceAsset: "asset.point.moppy",
    destinationAsset: "asset.point.nanaco",
    sourceUnits: 500,
    destinationUnits: 500,
    minimum: 500,
    increment: 500,
    processingMin: 0,
    processingMax: 3,
    locator: "Moppy exchange directory: nanaco Point row",
  }),
].sort((left, right) => left.claim_id.localeCompare(right.claim_id));

const roleResults = [];
for (const claim of claims) {
  const key = `${claim.family_id}\u0000${claim.source_role_id}`;
  let result = roleResults.find((item) => item.key === key);
  if (!result) {
    result = {
      key,
      family_id: claim.family_id,
      source_role_id: claim.source_role_id,
      outcome: "claims_found",
      source_ids: [],
      claim_ids: [],
      checked_at: observedAt,
      notes: "Every listed claim is bound to an official current exchange directory or detail page.",
    };
    roleResults.push(result);
  }
  result.source_ids.push(...claim.source_ids);
  result.claim_ids.push(claim.claim_id);
}
for (const result of roleResults) {
  result.source_ids = [...new Set(result.source_ids)].sort();
  result.claim_ids.sort();
  delete result.key;
}
roleResults.sort((left, right) =>
  `${left.family_id}\u0000${left.source_role_id}`.localeCompare(
    `${right.family_id}\u0000${right.source_role_id}`,
  ),
);

const counts = (key) =>
  Object.fromEntries(
    [...new Set(claims.map((claim) => claim[key]))]
      .sort()
      .map((value) => [
        value,
        claims.filter((claim) => claim[key] === value).length,
      ]),
  );

const artifact = {
  artifact_type: "p0_complex_route_benchmark_research",
  schema_version: "0.1",
  schema: {
    id: "p0-complex-route-benchmark-research-v0.1",
    required_root_keys: [
      "artifact_type",
      "schema_version",
      "schema",
      "metadata",
      "sources",
      "role_results",
      "claims",
      "summary",
    ],
    source_required_fields: [
      "source_id",
      "family_id",
      "roles",
      "url",
      "title",
      "publisher",
      "official_domain",
      "retrieval",
    ],
    claim_required_fields: [
      "claim_id",
      "family_id",
      "source_role_id",
      "source_ids",
      "claim_type",
      "subject",
      "predicate",
      "value",
      "applicability",
      "exclusions",
      "evidence_locator",
      "short_paraphrase",
    ],
    structured_transfer_required_fields: [
      "route_id",
      "operation",
      "source_asset_ref",
      "destination_asset_ref",
      "source_units",
      "destination_units",
      "minimum_source_units",
      "increment_source_units",
      "maximum_source_units_per_request",
      "maximum_source_units_per_period",
      "maximum_period",
      "fee_source_units",
      "processing_time_days_min",
      "processing_time_days_max",
      "cancellation_policy",
      "validity",
      "prerequisite_ids",
      "requires_rule_ids",
      "required_conditions_ja",
      "requires_direct_source",
      "partial_consumption",
    ],
    role_result_outcomes: [
      "claims_found",
      "partially_checked",
      "no_economic_claim_found",
    ],
    sort_order:
      "sources by source_id; role_results by family_id then source_role_id; claims by claim_id",
    source_policy:
      "First-party official programme and exchange pages only; no discovery page or search snippet is claim evidence.",
    quote_policy:
      "No verbatim quotation fields are used; evidence_locator identifies the official page section.",
  },
  metadata: {
    artifact_id: "p0-exchange-route-completeness.research.v0.1",
    protocol_version: "0.1",
    task_id: "production.exchange-route-expansion.v1",
    producer: "codex-official-source-research",
    families: [...new Set(claims.map((claim) => claim.family_id))].sort(),
    declared_roles: [
      "eligible_accounts",
      "eligible_cards",
      "transfer_partner_directory",
    ],
    bounded_run: {
      started_at: "2026-08-25T21:00:00+09:00",
      ended_at: "2026-08-25T21:40:00+09:00",
      timezone: "Asia/Tokyo",
      scope:
        "Official Recruit, JAL, ANA, JR Kyushu and Moppy pages were checked for production routes between assets declared in the unified graph.",
      truncation:
        "Only rows whose arithmetic and applicability are exact are executable. Unresolved provider details remain explicit production coverage gaps.",
      retrieval_cutoff: "2026-08-25",
    },
    publisher_policy:
      "Official operator pages only; search results were used solely to locate those pages.",
    pii_or_secret_check:
      "No credentials, account identifiers, membership data, tokens or payment data included.",
  },
  sources: sources.sort((left, right) =>
    left.source_id.localeCompare(right.source_id),
  ),
  role_results: roleResults,
  claims,
  summary: {
    claim_count: claims.length,
    source_count: sources.length,
    role_result_count: roleResults.length,
    claim_count_by_family: counts("family_id"),
    claim_count_by_role: counts("source_role_id"),
    claim_count_by_type: counts("claim_type"),
    failures: [],
    validation_intent:
      "Every executable directory row must compile to a source-bound graph edge and every prerequisite must remain explicit.",
  },
};

const rendered = `${JSON.stringify(artifact, null, 2)}\n`;
if (process.argv.includes("--check")) {
  if (!existsSync(target) || readFileSync(target, "utf8") !== rendered)
    throw new Error("Production exchange-route research fixture is stale");
} else {
  writeFileSync(target, rendered, "utf8");
}
