-- Staged from db/seeds/004_p0_payment_acceptance_batch.sql; edit the canonical source, not this file.
-- Generated by scripts/generate_p0_payment_acceptance_seed.mjs.
-- One bounded manual Agent Feed run expands only the already evidenced
-- Seven-Eleven payment-acceptance family set. It publishes no earning rate,
-- campaign, selectable product SKU, or canonical RewardRuleVersion.

begin;

do $seed$
declare
    v_receipt_id uuid;
    v_observation_id uuid;
    v_mapping_status text;
    v_evidence jsonb := $evidence${
  "artifact": {
    "media_type": null,
    "size_bytes": null,
    "uri": null
  },
  "captured_at": "2026-08-21T13:49:24+09:00",
  "content_hash": "sha256:b4eeb2c6869c288f4d14e89e74a10674a093ae6758d8deb01337ba49b9722460",
  "evidence_id": "ev_p0_seveneleven_payment_methods_20260821",
  "excerpt": null,
  "handling": {
    "contains_personal_data": false,
    "contains_secrets": false,
    "redistribution_restricted": false
  },
  "kind": "web",
  "locator": {
    "page": null,
    "type": "manual_note",
    "value": "Normalized payment-family labels from a bounded current-source check; no source excerpt retained."
  },
  "metadata": {
    "capture_method": "manual_capture",
    "local_snapshot_path": "fixtures/m3/agent-feed/p0-seveneleven-payment-methods.normalized-source.v0.1.json",
    "local_snapshot_size_bytes": 965,
    "publication_lane": "provisional_only",
    "record_type": "normalized_manual_source_snapshot",
    "source_snapshot_id": "snap_p0_seveneleven_payment_methods_20260821"
  },
  "published_at": null,
  "source": {
    "publisher": "Seven-Eleven Japan",
    "source_id": "merchant.seveneleven.payment-methods",
    "title": "ご利用可能なお支払方法",
    "uri": "https://www.sej.co.jp/services/cash.html"
  }
}$evidence$::jsonb;
begin
    if exists (
        select 1 from app_private.agent_feed_receipts
         where event_id = 'event_9cf61afbfddb1984d59470024e999b72d303eef8feb2f3ae6cc1303600fa9b70'
    ) or exists (
        select 1 from app_private.source_observations
         where observation_key = 'so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197'
            or semantic_fingerprint = 'sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c'
    ) then
        raise exception 'P0 payment-family source run already exists; seed is one-time and drift-sensitive';
    end if;

    insert into app_private.agent_feed_receipts (
        event_id, protocol_version, stream_id, run_id, finding_id, event_type,
        received_at, payload_hash, raw_payload, retention_class, purge_after,
        delivery_id, signature_timestamp, signature_key_id, delivery_attempt,
        transport_payload_hash, signature_verified
    ) values (
        'event_9cf61afbfddb1984d59470024e999b72d303eef8feb2f3ae6cc1303600fa9b70', '0.1',
        'merchant.jp-convenience', 'run_p0_seveneleven_payment_families_20260821',
        'finding_p0_seveneleven_payment_families_20260821', 'finding.submitted',
        '2026-08-21T04:51:00.000Z', 'sha256:1323f959f8da89ff4ef44edc26670fcea20f9634292fa217dfb172b0c6fb1ea2',
        $payload${
  "finding": {
    "assessment": {
      "agent_confidence": 0.95,
      "evidence_completeness": "complete",
      "novelty": "known",
      "source_authority_claim": "primary"
    },
    "attributes": {
      "accepted_payment_families": [
        "barcode_payment",
        "brand_debit_card",
        "brand_prepaid_card",
        "credit_card",
        "gift_certificate",
        "id",
        "nanaco",
        "quo_card",
        "quicpay",
        "rakuten_edy",
        "transport_e_money"
      ],
      "change_kind": "merchant_acceptance",
      "merchant_id": "merchant.7eleven",
      "source_id": "merchant.seveneleven.payment-methods",
      "source_snapshot_id": "snap_p0_seveneleven_payment_methods_20260821"
    },
    "effective_time": {
      "effective_from": null,
      "effective_to": null,
      "occurred_at": null
    },
    "evidence_refs": [
      "ev_p0_seveneleven_payment_methods_20260821"
    ],
    "finding_id": "finding_p0_seveneleven_payment_families_20260821",
    "finding_type": "rewards.merchant_acceptance",
    "producer_dedupe_key": "merchant.7eleven|accepted_payment_methods|2026-08-21",
    "routing_tags": [
      "p0",
      "merchant-acceptance",
      "provisional"
    ],
    "security_flags": [],
    "subjects": [
      {
        "id": "merchant.7eleven",
        "name": "7-Eleven",
        "type": "merchant"
      }
    ],
    "summary": "The current first-party Seven-Eleven payment-methods page lists the recorded barcode, electronic-money, card, debit/prepaid, gift-certificate, and QUO payment families.",
    "title": "Seven-Eleven lists eleven accepted payment families"
  },
  "import_provenance": {
    "bundle_hash": "sha256:afdcb4dc495882f38a1c88c111c5a8dc9ecaaaccb164c3d07d09a8c0c5b0b3b0",
    "imported_at": "2026-08-21T04:51:00.000Z",
    "mode": "local_run_bundle_import"
  },
  "submitted_evidence": [
    {
      "artifact": {
        "media_type": null,
        "size_bytes": null,
        "uri": null
      },
      "captured_at": "2026-08-21T13:49:24+09:00",
      "content_hash": "sha256:b4eeb2c6869c288f4d14e89e74a10674a093ae6758d8deb01337ba49b9722460",
      "evidence_id": "ev_p0_seveneleven_payment_methods_20260821",
      "excerpt": null,
      "handling": {
        "contains_personal_data": false,
        "contains_secrets": false,
        "redistribution_restricted": false
      },
      "kind": "web",
      "locator": {
        "page": null,
        "type": "manual_note",
        "value": "Normalized payment-family labels from a bounded current-source check; no source excerpt retained."
      },
      "metadata": {
        "capture_method": "manual_capture",
        "local_snapshot_path": "fixtures/m3/agent-feed/p0-seveneleven-payment-methods.normalized-source.v0.1.json",
        "local_snapshot_size_bytes": 965,
        "publication_lane": "provisional_only",
        "record_type": "normalized_manual_source_snapshot",
        "source_snapshot_id": "snap_p0_seveneleven_payment_methods_20260821"
      },
      "published_at": null,
      "source": {
        "publisher": "Seven-Eleven Japan",
        "source_id": "merchant.seveneleven.payment-methods",
        "title": "ご利用可能なお支払方法",
        "uri": "https://www.sej.co.jp/services/cash.html"
      }
    }
  ]
}$payload$::jsonb,
        'local_run_bundle_import', '2026-09-20T04:51:00.000Z',
        'delivery_2c209d19959348f4e44f4fd1a45c6c39701ca365ab3f4f0ff589dabfc00d0d92', '2026-08-21T04:51:00.000Z',
        'local-run-bundle-unverified', 1, 'sha256:afdcb4dc495882f38a1c88c111c5a8dc9ecaaaccb164c3d07d09a8c0c5b0b3b0', false
    ) returning id into v_receipt_id;

    insert into app_private.agent_feed_delivery_attempts (
        receipt_id, delivery_id, attempt_number, attempted_at,
        signature_timestamp, signature_key_id, transport_payload_hash,
        outcome, diagnostic, redaction_status, redacted_at
    ) values (
        v_receipt_id, 'delivery_2c209d19959348f4e44f4fd1a45c6c39701ca365ab3f4f0ff589dabfc00d0d92', 1, '2026-08-21T04:51:00.000Z',
        '2026-08-21T04:51:00.000Z', 'local-run-bundle-unverified',
        'sha256:afdcb4dc495882f38a1c88c111c5a8dc9ecaaaccb164c3d07d09a8c0c5b0b3b0', 'replayed', '{}', 'complete', '2026-08-21T04:51:00.000Z'
    );

    select observation_id, mapping_status
      into v_observation_id, v_mapping_status
      from app_private.map_agent_feed_finding(
          v_receipt_id,
          'so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197',
          $sources$[
  "merchant.seveneleven.payment-methods"
]$sources$::jsonb,
          $subjects$[
  {
    "id": "merchant.7eleven",
    "name": "7-Eleven",
    "type": "merchant"
  }
]$subjects$::jsonb,
          'merchant_acceptance',
          $summary$The current first-party Seven-Eleven payment-methods page lists the recorded barcode, electronic-money, card, debit/prepaid, gift-certificate, and QUO payment families.$summary$,
          $effective${
  "occurred_at": null,
  "effective_from": null,
  "effective_to": null
}$effective$::jsonb,
          $assessment${
  "source_authority_claim": "primary",
  "evidence_completeness": "complete",
  "agent_confidence": 0.95
}$assessment$::jsonb,
          $evidence_refs$[
  "ev_p0_seveneleven_payment_methods_20260821"
]$evidence_refs$::jsonb,
          $attributes${
  "accepted_payment_families": [
    "barcode_payment",
    "brand_debit_card",
    "brand_prepaid_card",
    "credit_card",
    "gift_certificate",
    "id",
    "nanaco",
    "quo_card",
    "quicpay",
    "rakuten_edy",
    "transport_e_money"
  ],
  "change_kind": "merchant_acceptance",
  "merchant_id": "merchant.7eleven",
  "source_id": "merchant.seveneleven.payment-methods",
  "source_snapshot_id": "snap_p0_seveneleven_payment_methods_20260821"
}$attributes$::jsonb,
          $flags$[]$flags$::jsonb,
          'sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c', 1
      );
    if v_mapping_status is distinct from 'mapped' or v_observation_id is null then
        raise exception 'P0 payment-family finding did not map to a new observation';
    end if;

    update app_private.source_observations
       set status = 'needs_review'
     where id = v_observation_id;
    update app_private.source_observation_submitted_evidence
       set submitted_payload = v_evidence,
           promotion_status = 'lead_only'
     where observation_id = v_observation_id
       and agent_feed_evidence_id = 'ev_p0_seveneleven_payment_methods_20260821';
    if not found then
        raise exception 'P0 payment-family evidence lead is missing';
    end if;
end
$seed$;

select app_private.publish_provisional_candidate_batch(
    $batch${
  "version": "provisional-publication-batch.v1",
  "batch_id": "batch_p0_seveneleven_payment_families_20260821",
  "plan_sha256": "sha256:a59447525cb207838439a3cdb8b9cc22d19d875a650a64f50354137a78892003",
  "published_at": "2026-08-21T04:53:00Z",
  "batch_hash": "sha256:ec1d70a01eed2004edf2a7397461e9983a89172162cad05dd3a6b3eb4023482d",
  "members": [
    {
      "member_id": "p0_seveneleven_rakuten_edy",
      "candidate_hash": "sha256:0edaeeef02df950270f646941ab45a03028d8fb13b6a2e4e53356c9f75f79167",
      "definition_hash": "sha256:8ac0e55edf33fe392e283fad61a1e439cb5eaab6d68559112f2750e7e49db89a",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_rakuten_edy_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_rakuten_edy",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven 楽天Edy acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced 楽天Edy payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.rakuten_edy"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_rakuten_edy"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_barcode_payment",
      "candidate_hash": "sha256:1741be627b37546bc6b8a8c94bc81bc617047a3eb495bea771ca3eea56ca38ce",
      "definition_hash": "sha256:bf32efc04118a313c98a231d4ad0b530e6a50b204c71cebcb383c16bad35d4f2",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_barcode_payment_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_barcode_payment",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven バーコード決済 acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced バーコード決済 payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.barcode_payment"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_barcode_payment"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_nanaco",
      "candidate_hash": "sha256:27ea0ed660ab3ae23b04cc781d804cdce7de0cfda61a98ced8ff891326cb9114",
      "definition_hash": "sha256:90fc4b80507d127d5d64a871154dc989c002bef0927dc80c719889e24387ae17",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_nanaco_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_nanaco",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven nanaco acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced nanaco payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.nanaco"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_nanaco"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_brand_debit_card",
      "candidate_hash": "sha256:535ed6bca513dce9134370aeb556bb79378ea0fa6b2fcc4f9ae3ddef43fb56a6",
      "definition_hash": "sha256:d085dd3836884177876e47e96bbcaa12b5354c0938204eb252df3b6765cb3f8c",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_brand_debit_card_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_brand_debit_card",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven ブランドデビット acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced ブランドデビット payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.brand_debit_card"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_brand_debit_card"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_id",
      "candidate_hash": "sha256:6b1e9f81e65f538526ed5f6028c2e267fa6421725ad8a951c7fafc1498a2f018",
      "definition_hash": "sha256:3926ae571376581d27406fc2defa4b057a06fea780ca8f0344037a390c44a2ca",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_id_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_id",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven iD acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced iD payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.id"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_id"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_transport_e_money",
      "candidate_hash": "sha256:80ebeb1dcbe998f1badd6bebfd3013c387f9cfd50f5f506b6c2fef39284b4f89",
      "definition_hash": "sha256:1ef4b44b55c5343ad9e762be46cfccac9c7d2f415d22f74f4766e75636775e1d",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_transport_e_money_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_transport_e_money",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven 交通系電子マネー acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced 交通系電子マネー payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.transport_e_money"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_transport_e_money"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_brand_prepaid_card",
      "candidate_hash": "sha256:893b83f9dffb22f480aee5fb6d9035367c71990bb3a948121b9015b9217bbc77",
      "definition_hash": "sha256:ae31cf16098f13d4043ace1f2e5e1116ca0799bb4fb47ec5b96e5890580b2ff1",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_brand_prepaid_card_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_brand_prepaid_card",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven ブランドプリペイド acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced ブランドプリペイド payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.brand_prepaid_card"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_brand_prepaid_card"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_quicpay",
      "candidate_hash": "sha256:941b4dfae2e7130a7875d9501ed3d8c7c4b861c02729c3b000a07574aeaa0b2f",
      "definition_hash": "sha256:da2db7784420e0c0cce230f1df5f5f8285dec0ad01b6c151a875c098e60b8227",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_quicpay_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_quicpay",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven QUICPay acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced QUICPay payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.quicpay"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_quicpay"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_gift_certificate",
      "candidate_hash": "sha256:970cdee595e796a6e3973151b47b15fb61b633052deb4c93610b1c95b3281232",
      "definition_hash": "sha256:a6122d7baa408de6d382cc25b823a6afd9642adf58dd8005653a166f812c32d1",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_gift_certificate_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_gift_certificate",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven 共通商品券 acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced 共通商品券 payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.gift_certificate"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_gift_certificate"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_quo_card",
      "candidate_hash": "sha256:acac6f0f14899c4626fa4e9b0f24e54cbf1af583a5e54ad079b6f5193d21c0f5",
      "definition_hash": "sha256:e6b7e276cce049df6eb4c67349774aa78871ce6b77d8e6d3ca6ce72b10ba4f72",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_quo_card_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_quo_card",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven QUOカード acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced QUOカード payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.quo_card"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_quo_card"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    },
    {
      "member_id": "p0_seveneleven_credit_card",
      "candidate_hash": "sha256:dde9a8a11bda1400d834778bd172ece656fb1cdb5567e7f8b241304031f7c5ed",
      "definition_hash": "sha256:43d575f9eeecf2b99479116449225fa4f032fcd0cb92d92a90780cd0c14047b1",
      "candidate_payload": {
        "version": "provisional-rule-candidate.v1",
        "candidate_id": "candidate_p0_seveneleven_credit_card_20260821_v0_1",
        "observation_id": "so_finding_p0_seveneleven_payment_families_20260821_81fb0e1867d59197",
        "observation_fingerprint": "sha256:81fb0e1867d59197d932134ca5c94fe8f93018769dfda1d1ebe57df2bb41bf9c",
        "p0_family_id": "merchant.7eleven",
        "source_role_id": "accepted_payment_methods",
        "source_authority_role": "primary",
        "source_ids": [
          "merchant.seveneleven.payment-methods"
        ],
        "rule": {
          "rule_id": "rr_p0_seveneleven_accept_credit_card",
          "version": 1,
          "status": "under_review",
          "rule_type": "payment_acceptance",
          "name": "Seven-Eleven クレジットカード acceptance",
          "description": "Acceptance-only provisional candidate for the evidenced クレジットカード payment family.",
          "subject": {
            "entity_type": "merchant",
            "entity_id": "merchant.seveneleven"
          },
          "scope": {
            "countries": [
              "JP"
            ],
            "operation_types": [
              "merchant_purchase"
            ],
            "merchant_ids": [
              "merchant.seveneleven"
            ],
            "channels": [
              "in_store"
            ],
            "included_product_classes": [
              "ordinary"
            ],
            "excluded_product_classes": [],
            "tax_basis": "tax_inclusive"
          },
          "eligibility": {
            "operation_match": {
              "required_loyalty_program_ids": [],
              "excluded_payment_instrument_ids": [],
              "allowed_funding_source_ids": [],
              "excluded_funding_source_ids": [],
              "allowed_source_asset_ids": [],
              "excluded_source_asset_ids": [],
              "allowed_destination_asset_ids": [],
              "required_interfaces": [],
              "excluded_interfaces": [],
              "must_present_before_payment": false,
              "allowed_payment_instrument_ids": [
                "instrument.seveneleven.credit_card"
              ]
            },
            "user_conditions": [],
            "transaction_conditions": {
              "eligible_amount_basis": "not_applicable",
              "requires_single_operation": true
            },
            "campaign_conditions": {
              "entry_required": false,
              "targeted_offer": false,
              "identity_verification_required": false,
              "first_use_only": false
            }
          },
          "effect": {
            "decision": "allow",
            "effect_target": "operation_eligibility",
            "target_rule_ids": [],
            "target_stack_groups": [],
            "reason_code": "accepted_payment_family_credit_card"
          },
          "caps": [],
          "stacking": {
            "stack_group": "jp_cvs_002_payment_acceptance",
            "mode": "non_reward_acceptance",
            "precedence": 10,
            "conflicts_with_rule_ids": [],
            "requires_rule_ids": [],
            "notes": "Payment acceptance is intentionally non-financial."
          },
          "validity": {
            "valid_from": "2026-08-21T13:49:24+09:00",
            "valid_to": null,
            "timezone": "Asia/Tokyo",
            "recorded_at": "2026-08-21T13:52:00+09:00",
            "superseded_at": null
          },
          "provenance": {
            "evidence_ids": [
              "ev_p0_seveneleven_payment_methods_20260821"
            ],
            "minimum_source_tier": "T1_CANONICAL",
            "confidence": 0.95,
            "human_verified": false,
            "review_notes": "The first-party payment-methods page was checked in a bounded manual source run. This provisional rule carries no reward calculation."
          },
          "audit": {
            "created_at": "2026-08-21T13:51:00+09:00",
            "created_by": "p0-payment-family-extractor",
            "review_events": [],
            "required_review_modes": [
              "solo_dual_pass",
              "agent_challenged"
            ],
            "review_mode": null,
            "reviewed_at": null,
            "reviewed_by": null,
            "change_reason": "Machine-extracted payment-acceptance candidate for correction-driven provisional publication."
          }
        },
        "extractor": {
          "name": "p0-payment-family-extractor",
          "version": "0.1"
        },
        "machine_check": {
          "checker": "p0-payment-family-semantic-check",
          "checker_version": "0.1",
          "checked_at": "2026-08-21T04:52:00Z",
          "checks": {
            "representation_safe": true,
            "rule_structure": true,
            "rule_semantics": true,
            "observation_binding": true,
            "p0_coverage": true
          }
        }
      }
    }
  ]
}$batch$::jsonb
);

do $assert$
begin
    if (select count(*) from app_private.provisional_publication_batch_members
         where batch_id = 'batch_p0_seveneleven_payment_families_20260821') <> 11
       or (select count(*) from app_api.active_experimental_provisional_publications
            where batch_id = 'batch_p0_seveneleven_payment_families_20260821') <> 11
    then
        raise exception 'P0 payment-family batch did not publish all members';
    end if;
end
$assert$;

commit;
